'use client';

import { useCallback, useEffect, useState } from 'react';
import { Plus, Save, Trash2 } from 'lucide-react';
import { apiClient } from '@/lib/api';
import { cn } from '@/lib/cn';
import { AdminChannelTabs, channelLabel, type AdminChannel } from './AdminChannelTabs';

type RedirectRow = {
  id: string;
  channel: string;
  sourcePath: string;
  destinationUrl: string;
  statusCode: number;
  reason: string;
  autoGenerated?: boolean;
  isActive: boolean;
  hitCount?: number;
};

const STATUS_CODES = [301, 302, 410] as const;
const REASONS = ['MANUAL', 'SLUG_CHANGED', 'ARTICLE_DELETED', 'CONTENT_MERGED', 'GONE'] as const;

function pathKey(value: string): string {
  const raw = value.trim();
  if (!raw) return '';
  try {
    if (/^https?:\/\//i.test(raw)) {
      return new URL(raw).pathname.replace(/\/+$/, '') || '/';
    }
  } catch {
    /* ignore invalid URL */
  }
  const withSlash = raw.startsWith('/') ? raw : `/${raw}`;
  return withSlash.replace(/\/+$/, '') || '/';
}

function isObviousLoop(sourcePath: string, destinationUrl: string, statusCode: number): boolean {
  if (statusCode === 410) return false;
  const src = pathKey(sourcePath);
  const dest = pathKey(destinationUrl);
  return !!src && !!dest && src === dest;
}

export function AdminSeoRedirects() {
  const [channel, setChannel] = useState<AdminChannel>('RETAIL');
  const [rows, setRows] = useState<RedirectRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [sourcePath, setSourcePath] = useState('/');
  const [destinationUrl, setDestinationUrl] = useState('/');
  const [statusCode, setStatusCode] = useState(301);
  const [reason, setReason] = useState<string>('MANUAL');

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const list = await apiClient.get<RedirectRow[]>(`/blog/admin/redirects?channel=${channel}`);
      setRows(Array.isArray(list) ? list : []);
    } catch (e: unknown) {
      setRows([]);
      setError(e instanceof Error ? e.message : 'بارگذاری ریدایرکت‌ها ناموفق بود');
    } finally {
      setLoading(false);
    }
  }, [channel]);

  useEffect(() => {
    load();
  }, [load]);

  const create = async () => {
    if (isObviousLoop(sourcePath, destinationUrl, statusCode)) {
      setError('مبدأ و مقصد یکسان است — این ریدایرکت حلقه می‌سازد.');
      return;
    }
    setSaving('new');
    setError('');
    try {
      await apiClient.post('/blog/admin/redirects', {
        channel,
        sourcePath,
        destinationUrl: statusCode === 410 ? destinationUrl.trim() || 'gone:410' : destinationUrl,
        statusCode,
        reason: statusCode === 410 ? 'GONE' : reason,
      });
      setSourcePath('/');
      setDestinationUrl('/');
      setStatusCode(301);
      setReason('MANUAL');
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'افزودن ریدایرکت ناموفق بود');
    } finally {
      setSaving(null);
    }
  };

  const saveRow = async (row: RedirectRow) => {
    if (isObviousLoop(row.sourcePath, row.destinationUrl, row.statusCode)) {
      setError('مبدأ و مقصد یکسان است — این ریدایرکت حلقه می‌سازد.');
      return;
    }
    setSaving(row.id);
    setError('');
    try {
      await apiClient.patch(`/blog/admin/redirects/${row.id}`, {
        sourcePath: row.sourcePath,
        destinationUrl: row.statusCode === 410 ? row.destinationUrl.trim() || 'gone:410' : row.destinationUrl,
        statusCode: row.statusCode,
        reason: row.statusCode === 410 ? 'GONE' : row.reason,
        isActive: row.isActive,
      });
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'ذخیره ریدایرکت ناموفق بود');
    } finally {
      setSaving(null);
    }
  };

  const remove = async (id: string) => {
    if (!confirm('حذف این ریدایرکت؟')) return;
    setSaving(id);
    setError('');
    try {
      await apiClient.delete(`/blog/admin/redirects/${id}`);
      await load();
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'حذف ریدایرکت ناموفق بود');
    } finally {
      setSaving(null);
    }
  };

  const patchRow = (id: string, patch: Partial<RedirectRow>) =>
    setRows((p) => p.map((r) => (r.id === id ? { ...r, ...patch } : r)));

  const loopHint = isObviousLoop(sourcePath, destinationUrl, statusCode);

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-xl font-bold text-gray-900">سئو و ریدایرکت</h1>
          <p className="mt-1 text-sm text-gray-500">
            مدیریت ریدایرکت‌های {channelLabel(channel)} — کدهای ۳۰۱ / ۳۰۲ / ۴۱۰
          </p>
        </div>
        <AdminChannelTabs value={channel} onChange={setChannel} />
      </div>

      {error ? (
        <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>
      ) : null}

      <div className="card space-y-3 p-5">
        <h2 className="text-sm font-bold text-gray-800">افزودن ریدایرکت</h2>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-6">
          <div className="lg:col-span-2">
            <label className="mb-1 block text-xs text-gray-600">مسیر مبدأ</label>
            <input
              className="input-base w-full"
              dir="ltr"
              value={sourcePath}
              onChange={(e) => setSourcePath(e.target.value)}
              placeholder="/old-path"
            />
          </div>
          <div className="lg:col-span-2">
            <label className="mb-1 block text-xs text-gray-600">مقصد</label>
            <input
              className="input-base w-full"
              dir="ltr"
              value={destinationUrl}
              onChange={(e) => setDestinationUrl(e.target.value)}
              placeholder="/new-path"
              disabled={statusCode === 410}
            />
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-600">کد</label>
            <select
              className="input-base w-full"
              value={statusCode}
              onChange={(e) => setStatusCode(Number(e.target.value))}
            >
              {STATUS_CODES.map((code) => (
                <option key={code} value={code}>
                  {code}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="mb-1 block text-xs text-gray-600">دلیل</label>
            <select
              className="input-base w-full"
              value={statusCode === 410 ? 'GONE' : reason}
              onChange={(e) => setReason(e.target.value)}
              disabled={statusCode === 410}
            >
              {REASONS.map((r) => (
                <option key={r} value={r}>
                  {r}
                </option>
              ))}
            </select>
          </div>
        </div>
        {loopHint ? (
          <p className="text-xs text-amber-600">مبدأ و مقصد یکسان است؛ ثبت غیرفعال است.</p>
        ) : null}
        <button
          type="button"
          onClick={create}
          disabled={saving === 'new' || loopHint}
          className="btn btn-primary btn-md inline-flex items-center justify-center gap-2"
        >
          <Plus className="h-4 w-4" />
          افزودن
        </button>
      </div>

      <div className="card overflow-hidden p-0">
        <div className="flex items-center justify-between border-b border-gray-100 p-4">
          <h2 className="font-bold text-gray-900">لیست ریدایرکت‌ها</h2>
          <button type="button" onClick={load} className="btn btn-outline btn-sm" disabled={loading}>
            بروزرسانی
          </button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[880px] text-sm">
            <thead className="bg-gray-50 text-xs text-gray-500">
              <tr>
                {['مبدأ', 'مقصد', 'کد', 'دلیل', 'خودکار', 'فعال', 'hits', ''].map((h) => (
                  <th key={h} className="px-3 py-2 text-right font-semibold">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {loading ? (
                <tr>
                  <td colSpan={8} className="px-3 py-8 text-center text-gray-400">
                    در حال بارگذاری…
                  </td>
                </tr>
              ) : rows.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-3 py-8 text-center text-gray-400">
                    ریدایرکتی برای این کانال نیست
                  </td>
                </tr>
              ) : (
                rows.map((r) => {
                  const rowLoop = isObviousLoop(r.sourcePath, r.destinationUrl, r.statusCode);
                  return (
                    <tr key={r.id} className={cn(rowLoop && 'bg-amber-50/60')}>
                      <td className="px-3 py-2">
                        <input
                          className="input-base w-full text-xs"
                          dir="ltr"
                          value={r.sourcePath}
                          onChange={(e) => patchRow(r.id, { sourcePath: e.target.value })}
                        />
                      </td>
                      <td className="px-3 py-2">
                        <input
                          className="input-base w-full text-xs"
                          dir="ltr"
                          value={r.destinationUrl}
                          disabled={r.statusCode === 410}
                          onChange={(e) => patchRow(r.id, { destinationUrl: e.target.value })}
                        />
                      </td>
                      <td className="px-3 py-2">
                        <select
                          className="input-base text-xs"
                          value={r.statusCode}
                          onChange={(e) => patchRow(r.id, { statusCode: Number(e.target.value) })}
                        >
                          {STATUS_CODES.map((code) => (
                            <option key={code} value={code}>
                              {code}
                            </option>
                          ))}
                        </select>
                      </td>
                      <td className="px-3 py-2">
                        <select
                          className="input-base text-xs"
                          value={r.statusCode === 410 ? 'GONE' : r.reason}
                          disabled={r.statusCode === 410}
                          onChange={(e) => patchRow(r.id, { reason: e.target.value })}
                        >
                          {REASONS.map((reasonOpt) => (
                            <option key={reasonOpt} value={reasonOpt}>
                              {reasonOpt}
                            </option>
                          ))}
                        </select>
                      </td>
                      <td className="px-3 py-2 text-xs text-gray-500">
                        {r.autoGenerated ? 'بله' : 'خیر'}
                      </td>
                      <td className="px-3 py-2">
                        <input
                          type="checkbox"
                          checked={r.isActive}
                          onChange={(e) => patchRow(r.id, { isActive: e.target.checked })}
                          aria-label="فعال"
                        />
                      </td>
                      <td className="px-3 py-2 text-xs tabular-nums">
                        {(r.hitCount ?? 0).toLocaleString('fa-IR')}
                      </td>
                      <td className="px-3 py-2">
                        <div className="flex items-center gap-1.5">
                          <button
                            type="button"
                            className="btn btn-primary btn-sm inline-flex items-center gap-1"
                            disabled={saving === r.id || rowLoop}
                            onClick={() => saveRow(r)}
                          >
                            <Save className="h-3.5 w-3.5" />
                            ذخیره
                          </button>
                          <button
                            type="button"
                            className="btn btn-outline btn-sm text-error"
                            disabled={saving === r.id}
                            onClick={() => remove(r.id)}
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                        {rowLoop ? <p className="mt-1 text-[11px] text-amber-600">حلقه</p> : null}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
