import { MigrationInterface, QueryRunner } from 'typeorm';
import { asciiSlug } from '../../common/ascii-slug';
import { matchCategorySeed } from '../../modules/category/category-seo-seed';

/**
 * SEO + admin upgrade: discount window, dual-channel product content,
 * related products, category SEO fields, min-order floor, content backfill.
 * Additive / backward compatible. Does not drop legacy description.
 */
export class SeoAdminUpgrade1755410400001 implements MigrationInterface {
  name = 'SeoAdminUpgrade1755410400001';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);

    await queryRunner.query(`
      ALTER TABLE "products"
        ADD COLUMN IF NOT EXISTS "discountType" varchar NULL,
        ADD COLUMN IF NOT EXISTS "discountPercent" integer NULL,
        ADD COLUMN IF NOT EXISTS "discountAmount" bigint NULL,
        ADD COLUMN IF NOT EXISTS "discountStartsAt" TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS "discountEndsAt" TIMESTAMPTZ NULL,
        ADD COLUMN IF NOT EXISTS "retailFullContent" text NULL,
        ADD COLUMN IF NOT EXISTS "wholesaleFullContent" text NULL,
        ADD COLUMN IF NOT EXISTS "legacyContent" text NULL,
        ADD COLUMN IF NOT EXISTS "careInstructions" jsonb NULL,
        ADD COLUMN IF NOT EXISTS "faqItems" jsonb NULL,
        ADD COLUMN IF NOT EXISTS "allowBelowMoq" boolean NOT NULL DEFAULT false
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "product_related" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "productId" uuid NOT NULL,
        "relatedProductId" uuid NOT NULL,
        "sortOrder" integer NOT NULL DEFAULT 0,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "PK_product_related_id" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_product_related_pair" UNIQUE ("productId", "relatedProductId"),
        CONSTRAINT "FK_product_related_product" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_product_related_related" FOREIGN KEY ("relatedProductId") REFERENCES "products"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(
      `CREATE INDEX IF NOT EXISTS "IDX_product_related_productId" ON "product_related" ("productId")`,
    );

    await queryRunner.query(`
      ALTER TABLE "categories"
        ADD COLUMN IF NOT EXISTS "slug" varchar NULL,
        ADD COLUMN IF NOT EXISTS "nameEn" varchar NULL,
        ADD COLUMN IF NOT EXISTS "seoTitle" text NULL,
        ADD COLUMN IF NOT EXISTS "seoDescription" text NULL,
        ADD COLUMN IF NOT EXISTS "h1" text NULL,
        ADD COLUMN IF NOT EXISTS "introText" text NULL,
        ADD COLUMN IF NOT EXISTS "bottomContent" text NULL,
        ADD COLUMN IF NOT EXISTS "heroImage" text NULL,
        ADD COLUMN IF NOT EXISTS "heroImageAlt" text NULL,
        ADD COLUMN IF NOT EXISTS "ogImage" text NULL,
        ADD COLUMN IF NOT EXISTS "canonicalOverride" text NULL,
        ADD COLUMN IF NOT EXISTS "isIndexable" boolean NOT NULL DEFAULT true,
        ADD COLUMN IF NOT EXISTS "sortOrder" integer NOT NULL DEFAULT 0,
        ADD COLUMN IF NOT EXISTS "status" varchar NOT NULL DEFAULT 'ACTIVE',
        ADD COLUMN IF NOT EXISTS "faqItems" jsonb NULL,
        ADD COLUMN IF NOT EXISTS "wholesaleH1" text NULL,
        ADD COLUMN IF NOT EXISTS "wholesaleSeoTitle" text NULL,
        ADD COLUMN IF NOT EXISTS "wholesaleSeoDescription" text NULL,
        ADD COLUMN IF NOT EXISTS "wholesaleIntroText" text NULL,
        ADD COLUMN IF NOT EXISTS "wholesaleBottomContent" text NULL
    `);

    await queryRunner.query(`
      ALTER TABLE "seo_redirects"
        ADD COLUMN IF NOT EXISTS "autoGenerated" boolean NOT NULL DEFAULT false
    `);

    await queryRunner.query(`
      UPDATE "products"
      SET "legacyContent" = "description"
      WHERE "description" IS NOT NULL
        AND TRIM("description") <> ''
        AND ("legacyContent" IS NULL OR TRIM("legacyContent") = '')
    `);
    await queryRunner.query(`
      UPDATE "products"
      SET "retailFullContent" = COALESCE("retailFullContent", "description"),
          "wholesaleFullContent" = COALESCE("wholesaleFullContent", "description")
      WHERE "description" IS NOT NULL AND TRIM("description") <> ''
    `);

    await queryRunner.query(`
      UPDATE "products"
      SET "minOrderQty" = 6
      WHERE COALESCE("allowBelowMoq", false) = false
        AND COALESCE("minOrderQty", 0) < 6
    `);
    await queryRunner.query(`
      ALTER TABLE "products" ALTER COLUMN "minOrderQty" SET DEFAULT 6
    `);

    const categories: Array<{ id: string; name: string; slug: string | null }> =
      await queryRunner.query(`SELECT id, name, slug FROM "categories" WHERE "deletedAt" IS NULL`);
    const used = new Set(
      categories.map((c) => String(c.slug || '').trim()).filter(Boolean),
    );

    for (const cat of categories) {
      if (cat.slug) continue;
      const seed = matchCategorySeed(cat.name);
      let slug = seed?.slug || asciiSlug(cat.name, 'category');
      if (used.has(slug)) slug = `${slug}-${String(cat.id).slice(0, 8)}`;
      used.add(slug);
      if (seed) {
        await queryRunner.query(
          `UPDATE "categories" SET
            "slug" = $1,
            "h1" = $2,
            "seoTitle" = $3,
            "seoDescription" = $4,
            "introText" = $5,
            "bottomContent" = $6,
            "wholesaleH1" = $7,
            "wholesaleSeoTitle" = $8,
            "wholesaleSeoDescription" = $9,
            "wholesaleIntroText" = $10,
            "wholesaleBottomContent" = $11
           WHERE id = $12`,
          [
            slug,
            seed.retail.h1,
            seed.retail.seoTitle,
            seed.retail.seoDescription,
            seed.retail.introText,
            seed.retail.bottomContent,
            seed.wholesale.h1,
            seed.wholesale.seoTitle,
            seed.wholesale.seoDescription,
            seed.wholesale.introText,
            seed.wholesale.bottomContent,
            cat.id,
          ],
        );
      } else {
        await queryRunner.query(`UPDATE "categories" SET "slug" = $1 WHERE id = $2`, [
          slug,
          cat.id,
        ]);
      }
    }

    await queryRunner.query(`
      UPDATE "categories"
      SET "slug" = 'category-' || SUBSTRING(id::text, 1, 8)
      WHERE "slug" IS NULL OR TRIM("slug") = ''
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "UQ_categories_slug" ON "categories" ("slug")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_products_status" ON "products" ("status")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_products_updatedAt" ON "products" ("updatedAt")
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_products_categoryId" ON "products" ("categoryId")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_products_categoryId"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_products_updatedAt"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_products_status"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "UQ_categories_slug"`);
    await queryRunner.query(`ALTER TABLE "seo_redirects" DROP COLUMN IF EXISTS "autoGenerated"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "product_related"`);
    await queryRunner.query(`
      ALTER TABLE "products"
        DROP COLUMN IF EXISTS "discountType",
        DROP COLUMN IF EXISTS "discountPercent",
        DROP COLUMN IF EXISTS "discountAmount",
        DROP COLUMN IF EXISTS "discountStartsAt",
        DROP COLUMN IF EXISTS "discountEndsAt",
        DROP COLUMN IF EXISTS "retailFullContent",
        DROP COLUMN IF EXISTS "wholesaleFullContent",
        DROP COLUMN IF EXISTS "legacyContent",
        DROP COLUMN IF EXISTS "careInstructions",
        DROP COLUMN IF EXISTS "faqItems",
        DROP COLUMN IF EXISTS "allowBelowMoq"
    `);
    await queryRunner.query(`
      ALTER TABLE "categories"
        DROP COLUMN IF EXISTS "slug",
        DROP COLUMN IF EXISTS "nameEn",
        DROP COLUMN IF EXISTS "seoTitle",
        DROP COLUMN IF EXISTS "seoDescription",
        DROP COLUMN IF EXISTS "h1",
        DROP COLUMN IF EXISTS "introText",
        DROP COLUMN IF EXISTS "bottomContent",
        DROP COLUMN IF EXISTS "heroImage",
        DROP COLUMN IF EXISTS "heroImageAlt",
        DROP COLUMN IF EXISTS "ogImage",
        DROP COLUMN IF EXISTS "canonicalOverride",
        DROP COLUMN IF EXISTS "isIndexable",
        DROP COLUMN IF EXISTS "sortOrder",
        DROP COLUMN IF EXISTS "status",
        DROP COLUMN IF EXISTS "faqItems",
        DROP COLUMN IF EXISTS "wholesaleH1",
        DROP COLUMN IF EXISTS "wholesaleSeoTitle",
        DROP COLUMN IF EXISTS "wholesaleSeoDescription",
        DROP COLUMN IF EXISTS "wholesaleIntroText",
        DROP COLUMN IF EXISTS "wholesaleBottomContent"
    `);
    await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "minOrderQty" SET DEFAULT 5`);
  }
}
